apiVersion: v1
kind: ConfigMap
metadata:
  name: aqua-scanner-config
  namespace: aqua
data:  
  # Aqua Scanner IP/Domain/Servicename followed by HTTPS port.
  AQUA_SERVER: "aqua-web:443"

  # Scanner's private key for HTTPS and Mutual Auth with offline CyberCenter
  #AQUA_PRIVATE_KEY: "/opt/aquasec/ssl/key.pem"

  # Scanner's public key for HTTPS and Mutual Auth with offline CyberCenter
  #AQUA_PUBLIC_KEY: "/opt/aquasec/ssl/cert.pem"

  # Scanner's root CA cert for HTTPS and Mutual Auth. The root CA certificate file should be mutual for both CyberCenter and Scanner certificates
  #AQUA_ROOT_CA: "/opt/aquasec/ssl/ca.pem"

  # Set this to 1 to establish mTLS connection with CyberCenter
  #OFFLINE_CC_MTLS_ENABLE: "1"

  #health monitor is supported from SaaS scanner version 2407.4.20 and for on-prem 2022.4.613.7
  # enable below two values for health check monitor (liveness probe)
  #AQUA_HEALTH_MONITOR_ENABLED: "true"
  #AQUA_HEALTH_MONITOR_PORT: "8081"


